[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && node --import tsx/esm server.ts"
